version: "3.8"

services:
  bot:
    build: .
    container_name: zaberu_bot
    restart: "unless-stopped"
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
